### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by rohan-deshpande** [rohan-deshpande/three-proton#18]
Here's a bunch of things that should be done as part of the `v2.0.0` release

- ~Remove all behaviour `reset` methods and move logic to the constructors. I don't see a reason for these methods at all as they are not called internally anywhere and they are just making the API more confusing than it needs to be~ (Descoped, while I think these are a bit unnecessary, happy to leave this as it is for now)
- [x] Fix `initializer/Position` constructor and function doc blocks so they do not have argument mismatches
- [x] Fix up all `TODO` comments (Resolved by #26)
- [x] Create `Proton.fromJSON` static method that can create an entire system from JSON (Resolved by #21)
- [x] Remove all methods which use the `initialize` suffix. These have been replaced by methods that use the `initializer` suffix (Resolved by #20)
- [x] Remove the `renderer/*Render` compatibility classes, remove all methods which use the `render` suffix. These have been replaced by methods that use the `renderer` suffix (Resolved by #20)
- [x] Create `VectorVelocity` initializer and port tests (Resolved by #22)
- [x] Create `RadialVelocity` initializer and port tests (Resolved by #22)
- [x] Create `PolarVelocity` initializer and port tests (Resolved by #22)
- [x] Rename `name` property on all classes to `type` to align with `three`. Create a utility method to set the type on the class to the constructor name 
- [x] Update `p`, `v`, and `a`, props on the `Particle` class to `position`, `velocity`, `acceleration` in the interest of self documenting code (Resolved by #25)
- [x] Rename `math/ArraySpan` to `math/ColorSpan`, remove the color specific stuff from `math/ArraySpan`, it simply returns a random item from its internal array, it shouldn't have specific color logic in it (Resolved by #23)
- ~Replace `core/Pool` with `deePool`~ (descoped, see [#16](https://github.com/rohan-deshpande/three-proton/issues/16#issuecomment-448132525))
- ~Replace `events/EventDispatcher` with `EventEmitter`~ (descoped, see [#17](https://github.com/rohan-deshpande/three-proton/issues/17#issuecomment-448148838)) 
- [x] Set the integrator as a property on the core Proton instance and reference this in the emitter via `this.parent.integrator` (Resolved by #21)

**Comment by rohan-deshpande** [comment]
Resolved by #27
